import '../../global-styles/globals.css';
import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import { ModalContextProvider } from '@/contexts/ModalContext';

export const metadata = {
  title: 'Cerberus Project',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <ModalContextProvider>
        <Header />
        <main className="main">{children}</main>
        <Footer />
      </ModalContextProvider>
    </>
  );
}
